config/routes.rb
Ingredients::Application.routes.draw do
  # OmniAuth
  root to: "recipes#index"
  match "/signin", to: "sessions#new", as: "new_session"
  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/signout", to: "sessions#destroy", :as => "signout"
  resources :identities

  resources :ingredients
  resources :recipes do
    resources :used_ingredients    
  end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :used_ingredients
  has_many :ingredients, :through => :used_ingredients
  
  validates_presence_of :name, :yield
  validates_numericality_of :yield
  
  def cost
    cost = 0
    self.used_ingredients.each do |used_ingredient|
      cost += used_ingredient.cost
    end
    return cost
  end
  
  def cost_each
    return self.cost/self.yield
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :authenticate
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.order('name')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :yield %><br />
    <%= f.text_field :yield %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<% title "Edit Recipe Name" %>

<%= render 'form' %>
<p>
  <%= link_to 'Delete Recipe', @recipe, confirm: 'Are you sure?', method: :delete %>  
</p>
<hr />
<p>
  <%= link_to 'Go Back', @recipe %>  
</p>

app/views/recipes/index.html.erb
<% title "Recipes" %>

<table>
  <tr>
    <th>Recipe</th>
    <th>Yield</th>
    <th>Cost Each</th>
    <th>Total Cost</th>
  </tr>
<% @recipes.each do |recipe| %>
  <tr>
    <td><%= link_to recipe.name, recipe %></td>
    <td><%= number_with_precision(recipe.yield, :precision => 0) %></td>
    <td><%= number_to_currency(recipe.cost_each) %></td>
    <td><%= number_to_currency(recipe.cost) %></td>
  </tr>
<% end %>
</table>
<hr />
<p>
  <%= link_to 'New Recipe', new_recipe_path %>
</p>

app/views/recipes/new.html.erb
<% title "New Recipe" %>

<%= render 'form' %>

<hr />
<p>
  <%= link_to 'Go Back', recipes_path %>
</p>

app/views/recipes/show.html.erb
<% title @recipe.name %>
<table>
  <tr>
    <th>Ingredient</th>
    <th>Amount</th>
    <th>Cost</th>
    <th></th>
    <th></th>
  </tr>
<% @recipe.used_ingredients.sort_by{|u| u.ingredient.name }.each do |used_ingredient| %>
  <tr>
    <td><%= link_to used_ingredient.ingredient.name, [@recipe, used_ingredient] %></td>
    <td><%= used_ingredient.entered_amount %></td>
    <td><%= number_to_currency(used_ingredient.cost) %></td>
    <td><%= link_to 'Edit', edit_recipe_used_ingredient_path(@recipe, used_ingredient) %></td>
    <td><%= link_to 'Delete', [@recipe, used_ingredient], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<p>
  <%= link_to 'Add Ingredient', new_recipe_used_ingredient_path(@recipe) %>  
</p>
<p>
  <strong>Yield:</strong> <%= number_with_precision(@recipe.yield, :precision => 0) %><br />
  <strong>Cost Each:</strong> <%= number_to_currency(@recipe.cost_each) %><br />
  <strong>Total Cost:</strong> <%= number_to_currency(@recipe.cost) %>
</p>
<hr />
<p>
  <%= link_to 'Edit Recipe', edit_recipe_path(@recipe) %>
</p>