config/routes.rb
Ingredients::Application.routes.draw do
  # OmniAuth
  root to: "recipes#index"
  match "/signin", to: "sessions#new", as: "new_session"
  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/signout", to: "sessions#destroy", :as => "signout"
  resources :identities

  resources :ingredients
  resources :recipes do
    resources :used_ingredients    
  end
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :used_ingredients
  has_many :recipes, :through => :used_ingredients
  
  validates_presence_of :name, :entered_amount, :cost
  validates_numericality_of :cost
  
  before_validation :set_units
  
  def set_units
    unless self.entered_amount.blank?
      ruby_unit = Unit.new(self.entered_amount)
      self.amount = ruby_unit.scalar
      self.units = ruby_unit.unit_name
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_filter :authenticate
  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.order('name')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingredients }
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.json
  def new
    @ingredient = Ingredient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/1/edit
  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(params[:ingredient])

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render json: @ingredient, status: :created, location: @ingredient }
      else
        format.html { render action: "new" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.json
  def update
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :ok }
    end
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>
      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :entered_amount, 'Amount' %><br />
    <%= f.text_field :entered_amount, :placeholder => 'Ex. 14.5 oz, 1 gallon, 2 lb' %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<% title "Edit Ingredient" %>

<%= render 'form' %>
<p>
  <%= link_to 'Delete Ingredient', @ingredient, confirm: 'Are you sure?', method: :delete %>
</p>
<hr />
<p>
  <%= link_to 'Go Back', @ingredient %>
</p>

app/views/ingredients/index.html.erb
<% title "Ingredients" %>

<table>
  <tr>
    <th>Name</th>
    <th>Amount</th>
    <th>Cost</th>
  </tr>
<% @ingredients.each do |ingredient| %>
  <tr>
    <td><%= link_to ingredient.name, ingredient %></td>
    <td><%= ingredient.entered_amount %></td>
    <td><%= number_to_currency(ingredient.cost) %></td>
  </tr>
<% end %>
</table>
<hr />
<p>
  <%= link_to 'New Ingredient', new_ingredient_path %>
</p>

app/views/ingredients/new.html.erb
<% title "New Ingredient" %>

<%= render 'form' %>

<hr />
<p>
  <%= link_to 'Go Back', ingredients_path %>
</p>

app/views/ingredients/show.html.erb
<% title @ingredient.name %>

<p style="font-size: 1.4em;">
  <strong><%= @ingredient.entered_amount %></strong> for <strong><%= number_to_currency(@ingredient.cost) %></strong>
</p>
<p style="color: #888;">
  <strong>Amount:</strong> <%= @ingredient.amount %><br />
  <strong>Units:</strong> <%= @ingredient.units %><br />
  <strong>Cost:</strong> <%= @ingredient.cost %>
</p>
<hr />
<p>
  <%= link_to 'Edit Ingredient', edit_ingredient_path(@ingredient) %>
</p>