config/routes.rb
Ingredients::Application.routes.draw do
  # OmniAuth
  root to: "recipes#index"
  match "/signin", to: "sessions#new", as: "new_session"
  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/signout", to: "sessions#destroy", :as => "signout"
  resources :identities

  resources :ingredients
  resources :recipes do
    resources :used_ingredients    
  end
end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  before_filter :authenticate
  
  def new
    @identity = env['omniauth.identity']
  end
  
  def index
    @identities = Identity.all
  end
  
  def destroy
    @identity = Identity.find(params[:id])
    @identity.destroy

    respond_to do |format|
      format.html { redirect_to identities_url }
      format.json { head :ok }
    end
  end
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/views/identities/index.html.erb
<% title "Accounts" %>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
  </tr>
<% @identities.each do |identity| %>
  <tr>
    <td><%= identity.name %></td>
    <td><%= identity.email %></td>
    <td><%= link_to 'Delete', identity, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<hr />
<p>
  <%= link_to "New Account", new_identity_path %>
</p>

app/views/identities/new.html.erb
<% title "New Account" %>

<%= form_tag "/auth/identity/register" do %>
  <% if @identity && @identity.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@identity.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
      <% @identity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= label_tag :name %><br>
    <%= text_field_tag :name, @identity.try(:name) %>
  </div>
  <div class="field">
    <%= label_tag :email %><br>
    <%= text_field_tag :email, @identity.try(:email) %>
  </div>
  <div class="field">
    <%= label_tag :password %><br>
    <%= password_field_tag :password %>
  </div>
  <div class="field">
    <%= label_tag :password_confirmation %><br>
    <%= password_field_tag :password_confirmation %>
  </div>
  <div class="actions"><%= submit_tag "Register" %></div>
<% end %>