config/routes.rb
Ingredients::Application.routes.draw do
  # OmniAuth
  root to: "recipes#index"
  match "/signin", to: "sessions#new", as: "new_session"
  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/signout", to: "sessions#destroy", :as => "signout"
  resources :identities

  resources :ingredients
  resources :recipes do
    resources :used_ingredients    
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) + " - Ingredients" || "Ingredients" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <h1 id="title"><%= link_to 'Ingredients', '/' %></h1>
    <div id="nav">
      <%= link_to 'Recipes', recipes_path, :id => 'recipes_link', :class => params[:controller] %>
      <%= link_to 'Ingredients', ingredients_path, :id => 'ingredients_link', :class => params[:controller] %>
      <%= link_to 'Accounts', identities_path, :id => 'identities_link', :class => params[:controller] %>
      <% if current_user %>
        <span style="float: right;"><%= current_user.name %> | <%= link_to "Sign out", signout_path %></span>
      <% end %>
    </div>
    <div id="container">
      <%= content_tag :h1, yield(:title) if show_title? %>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
    <div id="footer"><%= link_to '@brianpattison', 'http://twitter.com/brianpattison', :target => '_blank' %></div>
  </body>
</html>